"""
Generated by restcodegen (https://github.com/ValeriyMenshikov/restcodegen).

    source: {{ service_name|to_snake_case }}
    version: {{ version }}

    Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

from enum import Enum
from typing import Any
from uuid import UUID

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field, field_validator


class BadRequestError(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    message: str | None = Field(None, description="Client message")
    invalid_properties: dict[str, list[str]] | None = Field(
        None,
        alias="invalidProperties",
        description="Key-value pairs of invalid request properties",
    )


class BbParseMode(Enum):
    COMMON = "Common"
    INFO = "Info"
    POST = "Post"
    CHAT = "Chat"


class ChangeEmail(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    login: str | None = Field(None, description="User login")
    password: str | None = Field(None, description="User password")
    email: str | None = Field(None, description="New user email")


class ChangePassword(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    login: str | None = Field(None, description="User login")
    token: UUID | None = Field(None, description="Password reset token")
    old_password: str | None = Field(None, alias="oldPassword", description="Old password")
    new_password: str | None = Field(None, alias="newPassword", description="New password")


class ColorSchema(Enum):
    MODERN = "Modern"
    PALE = "Pale"
    CLASSIC = "Classic"
    CLASSIC_PALE = "ClassicPale"
    NIGHT = "Night"


class GeneralError(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    message: str | None = Field(None, description="Client message")


class InfoBbText(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    value: str | None = Field(None, description="Text")
    parse_mode: BbParseMode | None = Field(None, alias="parseMode")


class LoginCredentials(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    login: str | None = None
    password: str | None = None
    remember_me: bool | None = Field(None, alias="rememberMe")


class PagingSettings(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    posts_per_page: int | None = Field(None, alias="postsPerPage", description="Number of posts on a game room page")
    comments_per_page: int | None = Field(
        None,
        alias="commentsPerPage",
        description="Number of commentaries on a game or a topic page",
    )
    topics_per_page: int | None = Field(
        None,
        alias="topicsPerPage",
        description="Number of detached topics on a forum page",
    )
    messages_per_page: int | None = Field(
        None,
        alias="messagesPerPage",
        description="Number of private messages and conversations on dialogue page",
    )
    entities_per_page: int | None = Field(None, alias="entitiesPerPage", description="Number of other entities on page")


class Rating(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    enabled: bool | None = Field(None, description="Rating participation flag")
    quality: int | None = Field(None, description="Quality rating")
    quantity: int | None = Field(None, description="Quantity rating")


class Registration(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    login: str | None = Field(None, description="Login")
    email: str | None = Field(None, description="Email")
    password: str | None = Field(None, description="Password")


class ResetPassword(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    login: str | None = Field(None, description="Login")
    email: str | None = Field(None, description="Email")


class UserRole(Enum):
    GUEST = "Guest"
    PLAYER = "Player"
    ADMINISTRATOR = "Administrator"
    NANNY_MODERATOR = "NannyModerator"
    REGULAR_MODERATOR = "RegularModerator"
    SENIOR_MODERATOR = "SeniorModerator"


class UserSettings(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    color_schema: ColorSchema | None = Field(None, alias="colorSchema")
    nanny_greetings_message: str | None = Field(
        None,
        alias="nannyGreetingsMessage",
        description="Message that user's newbies will receive once they are connected",
    )
    paging: PagingSettings | None = None


class User(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    login: str | None = Field(None, description="Login")
    roles: list[UserRole] | None = Field(None, description="Roles")
    medium_picture_url: str | None = Field(None, alias="mediumPictureUrl", description="Profile picture URL M-size")
    small_picture_url: str | None = Field(None, alias="smallPictureUrl", description="Profile picture URL S-size")
    status: str | None = Field(None, description="User defined status")
    rating: Rating | None = None
    online: AwareDatetime | None = Field(None, description="Last seen online moment")
    name: str | None = Field(None, description="User real name")
    location: str | None = Field(None, description="User real location")
    registration: AwareDatetime | None = Field(None, description="User registration moment")


class UserDetails(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    login: str | None = Field(None, description="Login")
    roles: list[UserRole] | None = Field(None, description="Roles")
    medium_picture_url: str | None = Field(None, alias="mediumPictureUrl", description="Profile picture URL M-size")
    small_picture_url: str | None = Field(None, alias="smallPictureUrl", description="Profile picture URL S-size")
    status: str | None = Field(None, description="User defined status")
    rating: Rating | None = None
    online: AwareDatetime | None = Field(None, description="Last seen online moment")
    name: str | None = Field(None, description="User real name")
    location: str | None = Field(None, description="User real location")
    registration: AwareDatetime | None = Field(None, description="User registration moment")
    icq: str | None = Field(None, description="User ICQ number")
    skype: str | None = Field(None, description="User Skype login")
    original_picture_url: str | None = Field(
        None, alias="originalPictureUrl", description="URL of profile picture original"
    )
    info: InfoBbText | None = None
    settings: UserSettings | None = None

    @field_validator("info", mode="before")
    @classmethod
    def _empty_info_to_none(cls, value: Any) -> Any:
        # The API serializes an absent InfoBbText as an empty string rather than
        # null/object; normalize it so it matches the schema's object type.
        # See api-notes.md. (Manual patch: not emitted by restcodegen.)
        if value == "":
            return None
        return value


class UserDetailsEnvelope(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    resource: UserDetails | None = None
    metadata: Any | None = Field(None, description="Additional metadata")


class UserEnvelope(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    resource: User | None = None
    metadata: Any | None = Field(None, description="Additional metadata")
